[build]
  base = "client"
  command = "CI=false npm run build"
  publish = "build"
  environment = { REACT_APP_API_URL = "https://zvertexai-orzv.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200