[build]
  base = "client"
  command = "npm run build"
  publish = "client/build"
  environment = { NODE_VERSION = "16" }

[build.environment]
  REACT_APP_API_URL = "https://zvertexai-orzv.onrender.com"
  REACT_APP_STRIPE_PUBLIC_KEY = "pk_live_51R0u7fRr16KPJ9OnPwlpNKyHkwGHnvtZqibd2PWsxgkgqyzYOmx4AZE69YTmsrqpI5fk5aCSj04972mddYaBR8da004FxbliCE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200