[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://zvertexai-orzv.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://zvertexai.com/*"
  to = "https://zvertexai.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.zvertexai.com/*"
  to = "https://zvertexai.com/:splat"
  status = 301
  force = true