[build]
  base = "client"
  command = "npm run build"
  publish = "client/build"
  environment = { REACT_APP_API_URL = "https://zvertexai-orzv.onrender.com" }

[[redirects]]
  from = "/api/*"
  to = "https://zvertexai-orzv.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200