[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://zvertexai-orzv.onrender.com/api/:splat"  # Your Render URL
  status = 200
  force = true