[build]
  base = "client"  # Set the base directory to client/
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://zvertexai-orzv.onrender.com"  # Replace with your Render URL
  status = 200
  force = true