[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.2"
  REACT_APP_API_URL = "https://zvertexai-orzv.onrender.com"
  REACT_APP_STRIPE_PUBLIC_KEY = "pk_test_your_stripe_public_key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200